[workspace]
resolver = "3"
members = [
  "crates/parsyng-quote-macros",
  "crates/parsyng-proc-macros",
  "crates/parsyng-core",

  "benches",
  "benches/bench-comptime",
  "benches/bench-quote-comptime",

  "examples/simple-use",
  "examples/simple-use-macros",
]

[package]
name = "parsyng"
version = "0.1.0"
edition = "2024"
license = "MIT"
readme = "README.md"
keywords = ["macros", "proc"]
categories = ["development-tools::procedural-macro-helpers"]

[dependencies]
parsyng-proc-macros = { path = "./crates/parsyng-proc-macros" }
parsyng-core = { path = "./crates/parsyng-core" }

[features]
proc-macro2 = ["parsyng-core/proc-macro2"]
debug-pretty = ["parsyng-core/debug-pretty"]

[[bench]]
name = "parsyng-quote"
