[workspace]
resolver = "3"
members = [
  "crates/parsyng-quote-macros",
  "crates/parsyng-proc-macros",
  "crates/parsyng-core",

  "benches",
  "benches/bench-comptime",
  "benches/bench-quote-comptime",

  "examples/simple-use",
  "examples/simple-use-macros",
  "examples/heapsize/heapsize",
  "examples/heapsize/heapsize-macros",
  "examples/heapsize/example",
  "examples/debug-attribute/debug-attribute-macros",
  "examples/debug-attribute/example",
]

[package]
name = "parsyng"
description = "Procedural macro parsyng"
version = "0.1.0"
edition = "2024"
license = "MIT"
readme = "README.md"
repository = "https://github.com/supersurviveur/parsyng"
keywords = ["macros", "proc", "quote"]
categories = ["development-tools::procedural-macro-helpers"]

[dependencies]
parsyng-proc-macros = { path = "./crates/parsyng-proc-macros" }
parsyng-core = { path = "./crates/parsyng-core" }

[dev-dependencies]
quote = "1"

[features]
proc-macro2 = ["parsyng-core/proc-macro2"]
debug-pretty = ["parsyng-core/debug-pretty"]

[[bench]]
name = "parsyng-quote"
required-features = ["proc-macro2"]
