//! Generic wrappers for content surrounded by a matching pair of delimiters:
//! [`Bracketed<T>`] (`[T]`), [`Braced<T>`] (`{T}`) and [`Parenthesized<T>`]
//! (`(T)`).
//!
//! All three are generated by the same `make_delimiters!` macro below and
//! share an identical API: they parse by first grabbing a [`Group`] with the
//! matching [`Delimiter`], then parsing `T` from its contents (erroring if
//! tokens are left over inside the group), and they convert back to tokens
//! by re-wrapping `T`'s tokens in a fresh group with that delimiter — so the
//! original group's span is not preserved on the round trip, only its kind.
//!
//! Reference: <https://doc.rust-lang.org/reference/tokens.html#delimiters>

use crate::ToTokens;
use crate::{
    error::{Diagnostics, Result},
    parse::{Parse, ParseBuffer},
    proc_macro::{Delimiter, Group, Span, TokenStream},
};

use std::ops::{Deref, DerefMut};

macro_rules! make_delimiters {
    ($($name:ident $l:literal $r:literal $delimiter:ident,)*) => {
        $(

        #[doc = concat!("`", $l, "T", $r, "`: a `T` surrounded by a matching `", $l, "` `", $r, "` pair.")]
        #[derive(Clone, Debug)]
        pub struct $name<T> {
            group: Group,
            content: T,
        }

        impl<T> $name<T> {
            /// Wrap an already-parsed `content` with the [`Group`] it came from.
            pub const fn new(group: Group, content: T) -> Self {
                Self { group, content }
            }
            /// The span of the delimited group (including the delimiters
            /// themselves).
            pub fn span(&self) -> Span {
                self.group.span()
            }
            /// Discard the delimiters and take ownership of the content.
            pub fn inner(self) -> T {
                self.content
            }
            /// Borrow the content without discarding the delimiters.
            pub const fn inner_ref(&self) -> &T {
                &self.content
            }
            /// Transform the content in place, keeping the same delimiter group.
            pub fn map<R, F: FnOnce(T) -> R>(self, f: F) -> $name<R> {
                $name::<R>::new(self.group, f(self.content))
            }
        }

        impl<T> Deref for $name<T> {
            type Target = T;

            fn deref(&self) -> &Self::Target {
                &self.content
            }
        }

        impl<T> DerefMut for $name<T> {
            fn deref_mut(&mut self) -> &mut Self::Target {
                &mut self.content
            }
        }

        impl<T: Parse> Parse for $name<T> {
            fn parse(input: &mut ParseBuffer) -> Result<Self> {
                match input.group() {
                    Some(group) if group.delimiter() == Delimiter::$delimiter => {
                        let mut stream = ParseBuffer::new(group.stream());
                        let content = stream.parse::<T>()?;

                        if stream.is_empty() {
                            Ok(Self { group, content })
                        } else {
                            Err(Diagnostics::new_error_spanned(
                                concat!("Expected `", $r, "`"),
                                stream.span(),
                            ))
                        }
                    }
                    _ => Err(Diagnostics::new_error_spanned(
                        concat!("Expected `", $l, "`"),
                        input.span(),
                    )),
                }
            }
        }
        impl<T: ToTokens> ToTokens for $name<T> {
            fn to_tokens(&self, tokens: &mut crate::proc_macro::TokenStream) {
                let mut inner_tokens = TokenStream::new();
                self.content.to_tokens(&mut inner_tokens);
                tokens.extend(Some(Group::new(Delimiter::$delimiter, inner_tokens)));
            }
        }
        )*
    };
}

make_delimiters! {
    Bracketed '[' ']' Bracket,
    Braced '{' '}' Brace,
    Parenthesized '(' ')' Parenthesis,
}
