[package]
name = "bench-quote-comptime"
description = "Demo program used to bench compilation time of quote in `parsyng`"
version = "0.1.0"
edition = "2024"
license = "MIT"
readme = "README.md"
repository = "https://github.com/supersurviveur/parsyng"
keywords = ["macros", "proc", "quote"]
categories = ["development-tools::procedural-macro-helpers"]

[lib]
proc-macro = true

[dependencies]
quote = { version = "1", optional = true }
unsynn = { version = "0.3", optional = true, default-features = false, features = ["proc_macro2"] }
parsyng-core = { path = "../../crates/parsyng-core", optional = true }

[features]
quote = ["dep:quote"]
unsynn = ["dep:unsynn"]
parsyng-core = ["dep:parsyng-core"]
proc-macro2 = ["parsyng-core/proc-macro2"]

empty = []
small = []
big = []
