[package]
name = "parsyng-core"
version = "0.1.0"
edition = "2024"
license = "MIT"
readme = "README.md"
keywords = ["macros", "proc"]
categories = ["development-tools::procedural-macro-helpers"]

[dependencies]
parsyng-quote-macros = { path = "../parsyng-quote-macros" }
unicode-ident = "1"

# Optional dependencies
proc-macro2 = { version = "1", optional = true }

[features]
proc-macro2 = ["dep:proc-macro2"]
debug-pretty = []
